dbca-wa/gis_kaartdijin_boodja

govapp/apps/catalogue/absorber.py
govapp/apps/catalogue/management/commands/absorb.py
govapp/apps/catalogue/management/commands/scan.py
govapp/apps/catalogue/scanner.py
govapp/settings.py

* Adds the scanner management command to absorb files from the staging area
* Usage: `python manage.py scan`
* This PR builds off #21, so contains those changes

Scanner management command

---

govapp/apps/catalogue/absorber.py

* As per the demo this morning, this is the improved create/update process as it currently exists

Improve catalogue entry create and update process

---

govapp/apps/accounts/serializers.py
govapp/apps/accounts/views.py
govapp/apps/catalogue/absorber.py
govapp/apps/catalogue/management/commands/absorb.py
govapp/apps/catalogue/management/commands/scan.py
govapp/apps/catalogue/permissions.py
govapp/apps/catalogue/scanner.py
govapp/apps/catalogue/serializers/catalogue_entries.py
govapp/apps/catalogue/views.py
govapp/apps/swagger/urls.py
govapp/settings.py

This PR includes large API improvements:
* Added tags to logically group api endpoints in swagger ui
* Added `/me` endpoint to users
* Added `/lock` and `/unlock` endpoints to catalogue entry
* Added model updating endpoints to catalogue entry
* Adjusted read-only/read-write fields on catalogue entry
* Added permissions for editing a catalogue entry
* This PR builds on #21 and #22 so contains those changes

Large API improvements

---

govapp/frontend/src/backend/backend.service.ts
govapp/frontend/src/backend/backend.stub.ts
govapp/frontend/src/components/CataloguePage.vue
govapp/frontend/src/components/dataTable/CatalogueEntryDataTable.vue
govapp/frontend/src/components/dataTable/NotificationDatatable.vue
govapp/frontend/src/components/detailViews/CatalogueEntryDetailView.vue
govapp/frontend/src/components/viewState.api.ts
govapp/frontend/src/components/widgets/CatalogueEntryFilter.vue
govapp/frontend/src/providers/NotificationProvider.api.ts
govapp/frontend/src/providers/catalogueEntryProvider.api.ts
govapp/frontend/src/providers/catalogueEntryProvider.ts
govapp/frontend/src/providers/layerSubmissionProvider.ts
govapp/frontend/src/providers/layerSubscriptionProvider.ts
govapp/frontend/src/stores/CatalogueEntryStore.ts

- Simplify navigation
- Back button
- Build fixes
- Less strings, more enums

Build fixes and more!

---

govapp/frontend/src/components/dataTable/CatalogueEntryDataTable.vue
govapp/frontend/src/components/dataTable/LayerSubmissionDataTable.vue
govapp/frontend/src/components/dataTable/LayerSubscriptionDataTable.vue
govapp/frontend/src/providers/layerSubmissionProvider.api.ts
govapp/frontend/src/providers/layerSubmissionProvider.ts
govapp/frontend/src/providers/layerSubscriptionProvider.api.ts
govapp/frontend/src/providers/layerSubscriptionProvider.ts
govapp/frontend/src/providers/providerCommon.api.ts
govapp/frontend/src/stores/CatalogueEntryStore.ts

Better fetching of CatalogueEntries

Link to CatalogueEntry from submission other tables

---

govapp/frontend/src/components/CataloguePage.vue
govapp/frontend/src/components/dataTable/LayerSubmissionDataTable.vue
govapp/frontend/src/components/widgets/FormSelect.vue
govapp/frontend/src/components/widgets/LayerSubmissionFilter.vue
govapp/frontend/src/providers/catalogueEntryProvider.ts
govapp/frontend/src/providers/layerSubmissionProvider.ts
govapp/frontend/src/providers/layerSubscriptionProvider.ts
govapp/frontend/src/providers/providerCommon.api.ts
govapp/frontend/src/stores/CatalogueEntryStore.ts
govapp/frontend/src/stores/LayerSubmissionStore.ts
govapp/frontend/src/stores/LayerSubscriptionStore.ts
govapp/frontend/src/tools/filterComposable.api.ts
govapp/frontend/src/tools/filterComposable.ts

- Add `clear all` button and functionality
- Adjust filtering

Clear all button

---

govapp/middleware.py
tests/settings.py

* Unit tests now output emails to console (just in case)
* Removed unused settings
* Fixed some linting issues

Fix unit test settings

---

govapp/apps/catalogue/absorber.py
govapp/apps/catalogue/emails.py
govapp/apps/catalogue/models/catalogue_entries.py
govapp/apps/catalogue/models/notifications.py
govapp/apps/catalogue/notifications.py
govapp/apps/catalogue/scanner.py
govapp/apps/catalogue/templates/catalogue_entry_locked_email.html
govapp/apps/catalogue/templates/catalogue_entry_locked_email.txt
govapp/apps/catalogue/utils.py
govapp/apps/emails/emails.py

* Adds new email for Catalogue Entry locking
* Implements actual functionality to the Email Notifications
* Abstracts notification sending and logic to `notifications.py`

Implement email notifications email functionality

---

govapp/apps/catalogue/emails.py
govapp/apps/catalogue/models/layer_submissions.py
govapp/apps/catalogue/models/notifications.py
govapp/apps/catalogue/notifications.py
govapp/apps/catalogue/webhooks.py
govapp/gis/conversions.py

* Registered Webhook notifications are POSTed to the registered URL, body is a GeoJSON of the layer

Webhook Notifications Implementation (Initial Attempt)

---

Dockerfile
poetry.lock
pyproject.toml

* Installs `ubuntugis/unstable` `GDAL` 3.6.2
* Updates `Poetry` to 1.3.2
* Downgrades project (and dependencies) back to Python 3.10

Update Dockerfile to install GDAL 3.6.2

---

poetry.lock
pyproject.toml

* This fixes the hardcoded Sharepoint API timeout issue (discussed via email).

Upgrade `shareplum` to git dependency pinned to latest commit.

---

govapp/apps/catalogue/absorber.py
govapp/apps/catalogue/models/catalogue_entries.py
govapp/apps/publisher/models/publish_entries.py

* Don't assume that an existing Catalogue Entry will always have a Publish Entry.

Fix Catalogue Entry Publish Entry Assumption

---

docs/backend.md

* Contains `docs/backend.md` handover documentation

Backend handover documentation

---

govapp/apps/catalogue/admin.py
govapp/apps/catalogue/permissions.py
govapp/static/js/kbcatalogue.js
govapp/templates/govapp/catalogue_entries_view.html
govapp/templates/govapp/catalogue_entries_view_details.html
govapp/templates/govapp/catalogue_entries_view_symbology.html
govapp/urls.py
govapp/views.py

- Catalogue Tab 
- Catalogue Symbology View/Updates
- Remove editor/catalogue group permissions

Catalogue Updates

---

govapp/static/js/common.pagination.js
govapp/static/js/kbcatalogue.js
govapp/static/js/kbcatalogue.pagination.js
govapp/static/js/kbpublish.js
govapp/static/js/kbpublish.pagination.js
govapp/templates/govapp/base.html
govapp/templates/govapp/catalogue_entries.html
govapp/templates/govapp/publish.html

- add common.pagination.js
- all pagination codes were moved to common.pagination.js
- all codes inside kbcatalogue.pagination.js and kbpublish.pagination.js were commented out.
- add a loading common.pagination.js line in base.html
- several changes were made for applying common pagination in catalogue_entries.html and publish.html
- some refactoring were made for applying common pagination in kbcatalogue.js and kbpublish.js

gather pagination logic into common.pagination.js & apply pagination to publish page.

---

govapp/apps/catalogue/directory_absorber.py
govapp/apps/logs/admin.py

and add columns on admin table of logs models

bug fix: change the source of metadata

---

govapp/apps/catalogue/directory_absorber.py

- to synchronize the codes of calling 'convert_to_geojson' in 'update_catalogue_entry' and 'create_catalogue_entry'

bug fix: set layer value from catalogu_entry

---

govapp/static/js/common.entity.modal.js
govapp/static/js/kbcatalogue.attribute.js
govapp/static/js/kbcatalogue.detail.js
govapp/static/js/kbcatalogue.js
govapp/static/js/kblayersubmission.js
govapp/static/js/kbpublish.js
govapp/static/js/table.js

- fix a bug of pagination when filtering
- add response check logic to several parts
- change set_row -> set_tbody for another task.

bug fix: filtering pagination  & resoponse check

---

govapp/apps/catalogue/views.py
govapp/static/js/common.entity.modal.js
govapp/static/js/kblayersubmission.js
govapp/templates/govapp/common_entity_modal.html

- change the default height of textarea bigger

progress modal is shown while downloading a file

---

govapp/apps/catalogue/filters.py
govapp/apps/catalogue/serializers/layer_subscriptions.py
govapp/apps/catalogue/views.py
govapp/static/js/kblayersubscription.js
govapp/static/js/utils.js
govapp/templates/govapp/layer_subscriptions.html
govapp/views.py

- add 'Assigned_To' filter on Subscription page
- added delete btn on the table of subscription
- hided delete btn of table by permission
- corrected time difference when converting

add 'Assigned_To' filter on Subscription page and a few updates

---

govapp/static/js/kbpublish.js
govapp/templates/govapp/publish_view_new_cddp.html

shibaken/main to dbca-wa/main
